- README.md
- src/content/config.ts
- src/content/projects/BigWarp.md
- src/project-template.md
- src/utils/githubApiHelper.js
- src/utils/tagManipulation.js
Also added the new frontmatter variables publication DOI array and publication text array
> Document additional steps for adding new tag category

- src/content/projects/neuVid.md
- src/content/projects/ossi-website.md
- src/content/projects/peta-scale-lightsheet-processing.md
- src/content/projects/spatial-transcriptomics-tools.md
- src/content/projects/vvd-viewer.md
- src/project-template.md
From here: https://www.janelia.org/open-science/overview/open-science-software-initiative-ossi/ossi-supported-projects
> Add all current ossi supported projects

- src/components/Footer.astro
> Footer includes link to Janelia homepage, wrapped around Janelia logo

- src/components/projects/FilterMenu.jsx
- src/pages/ecosystems/index.astro
- src/pages/projects/index.astro
Also changed up/down chevron icons to +/- icons - I thought it was a little more intuitive.
> FilterMenu categories closed by default

- README.md
> README includes updated instructions for adding project images

- src/content/config.ts
- src/content/projects/An-open-source-platform-for-single-molecule-localization.md
- src/content/projects/BigWarp.md
- src/content/projects/Cellpose-and-Suite2p.md
- src/content/projects/Java-packaging-tool-chain.md
- src/content/projects/Kilosort.md
- src/content/projects/Paintera.md
- src/content/projects/peta-scale-lightsheet-processing.md
- src/content/projects/spatial-transcriptomics-tools.md
- src/content/projects/video-annotation-library.md
- src/content/projects/vvd-viewer.md
- src/layouts/ProjectLayout.astro
- src/project-template.md
Added to frontmatter for projects and displayed on the individual project pages under additional information
> Add links to proposals for all ossi projects

- .github/actions/validTagsList.json
- src/content/projects/BigStream.md
Be sure to note the new project tab "Ahrens Lab"
> Add/edit BigStream

- src/components/projects/individual-project/QuickLinks.astro
> fix: GitHub issues URL now points to repo issues section

- src/components/projects/individual-project/Citation.astro
- src/pages/projects/[...slug].astro
- Ensures all Link components now utilize the `url` prop across project and page components
> fix: update Link component prop from href to url

- src/content/projects/neuronbridge.md
- Expanded tagline with details on modalities (EM/LM) and matching capabilities
- Updated maintainer contact format to include `mailto:`
- Changed installation instructions link to GitHub docs for more detailed setup info
- Added YouTube URL and caption for additional project insights
- Refreshed project description for clarity and comprehensiveness
> fix(neuronbridge): update NeuronBridge project details

- src/content/projects/bigstitcher.md
- src/content/projects/bigwarp.md
- src/content/projects/cellpose.md
- src/content/projects/kilosort.md
- src/content/projects/stitching-spark.md
- src/content/projects/suite2p.md
> content: add YT links to OSSI projects with available link

- src/pages/projects/index.astro
> style: randomize order of project cards on page refresh

- src/components/projects/CardContainer.jsx
- src/components/projects/stores/projectSearchResultsStore.js
- src/pages/projects.json.js
> layout: if search query, order cards by relevance score

- src/content/projects/an-open-source-platform-for-single-molecule-localization.md
- src/content/projects/bigstitcher-spark.md
- src/content/projects/bigstitcher.md
- src/content/projects/bigwarp.md
- src/content/projects/cellpose.md
- src/content/projects/easi-fish-pipeline.md
- src/content/projects/hortacloud.md
- src/content/projects/java-packaging-tool-chain.md
- src/content/projects/kilosort.md
- src/content/projects/neuvid.md
- src/content/projects/ossi-website.md
- src/content/projects/paintera.md
- src/content/projects/rs-fish.md
- src/content/projects/stim.md
- src/content/projects/stitching-spark.md
- src/content/projects/suite2p.md
- src/content/projects/video-annotation-library.md
- src/content/projects/vvd-viewer.md
> added OSSI project status for all projects

- src/components/individual-project/ExternalLinks.astro
- src/components/individual-project/Tabs.jsx
- src/layouts/BaseLayout.astro
- src/pages/projects/[...slug].astro
- src/scripts/fathomEvents.js
Theoretically tracks:
Internal link clicks:
-	Proposal PDF
-	README tab
-	embedded youtube
All external link clicks
> feat: add fathom tracking for events

- src/components/CallToAction.astro
- src/components/Hero.jsx
- src/components/TextBlock.astro
- src/pages/index.astro
> style: fixes hero overflow on smaller screens

- src/components/projects/FilterMenu.jsx
> fix: on small screens, x button now closes filter menu

- src/components/individual-project/Tabs.jsx
> style: extends project GH readme to full width

- src/content/projects/bigstream.md
[BigStream's](https://ossi.janelia.org/projects/bigstream/) "Reach out with a question" button resulted in a "page not found"
> Fix BigStream broken link

- package-lock.json
- package.json
- src/components/DisplayItem.astro
- src/components/ProposalListItem.astro
- src/components/blog/BlogImage.astro
- src/components/blog/BlogListItem.astro
- src/components/individual-project/Readme.jsx
- src/components/individual-project/RelatedPosts.astro
- src/content.config.ts
- src/layouts/BlogLayout.astro
- src/pages/blog/[...id].astro
- src/pages/ecosystems/[...id].astro
- src/pages/ecosystems/index.astro
- src/pages/projects/[id].astro
- src/pages/projects/index.astro
following the docs here https://docs.astro.build/en/guides/upgrade-to/v5/
> chore: update to Astro v5
